// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUCQyhcH82IF8lI3BLwxHstU_dKaMgVBc',
    appId: '1:601036232267:web:9cf3bf5bdc344346839fce',
    messagingSenderId: '601036232267',
    projectId: 'classproject-de011',
    authDomain: 'classproject-de011.firebaseapp.com',
    storageBucket: 'classproject-de011.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlRwjVuuRe_sMnrj9Zrkn-dgxfMmSp48w',
    appId: '1:601036232267:android:3b6435548b9f5fe1839fce',
    messagingSenderId: '601036232267',
    projectId: 'classproject-de011',
    storageBucket: 'classproject-de011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtNKNycErIMG4jx3dK5nuKeV2iPj0M16k',
    appId: '1:601036232267:ios:9c56d0a43b504588839fce',
    messagingSenderId: '601036232267',
    projectId: 'classproject-de011',
    storageBucket: 'classproject-de011.appspot.com',
    iosBundleId: 'com.example.classword',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtNKNycErIMG4jx3dK5nuKeV2iPj0M16k',
    appId: '1:601036232267:ios:671d8ae136763341839fce',
    messagingSenderId: '601036232267',
    projectId: 'classproject-de011',
    storageBucket: 'classproject-de011.appspot.com',
    iosBundleId: 'com.example.classword.RunnerTests',
  );
}
