"""Daily report: pre-market, intraday picks, options ideas, watch list."""
import json
from datetime import date
from pathlib import Path

from jinja2 import Template
from loguru import logger

REPORTS_DIR = Path(__file__).parent.parent.parent / "reports" / "daily"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

DAILY_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>India Quant Daily Report — {{ report_date }}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; background: #0d1117; color: #c9d1d9; margin: 0; padding: 20px; }
  h1 { color: #58a6ff; border-bottom: 1px solid #30363d; padding-bottom: 10px; }
  h2 { color: #3fb950; margin-top: 30px; }
  h3 { color: #d2a8ff; }
  .regime-badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-weight: bold; font-size: 14px; }
  .Bull { background: #1a3c1a; color: #3fb950; }
  .Bear { background: #3c1a1a; color: #f85149; }
  .Sideways { background: #2d2d1a; color: #e3b341; }
  .High-Vol { background: #3c1a3c; color: #d2a8ff; }
  .card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 16px; margin: 12px 0; }
  .long { border-left: 4px solid #3fb950; }
  .short { border-left: 4px solid #f85149; }
  table { width: 100%; border-collapse: collapse; margin: 10px 0; }
  th { background: #21262d; padding: 8px; text-align: left; color: #8b949e; font-size: 12px; }
  td { padding: 8px; border-bottom: 1px solid #21262d; }
  .risk-flag { background: #3c1a1a; color: #f85149; padding: 2px 8px; border-radius: 4px; font-size: 12px; }
  .metric { display: inline-block; margin: 4px 8px; }
  .metric-label { font-size: 11px; color: #8b949e; }
  .metric-value { font-size: 16px; font-weight: bold; }
  footer { margin-top: 40px; color: #8b949e; font-size: 12px; border-top: 1px solid #30363d; padding-top: 10px; }
</style>
</head>
<body>
<h1>🇮🇳 India Quant Daily Report — {{ report_date }}</h1>

<h2>Section 1: Market Regime Dashboard</h2>
<div class="card">
  <div class="metric">
    <div class="metric-label">Regime</div>
    <div class="metric-value"><span class="regime-badge {{ macro.regime_label }}">{{ macro.regime_label }}</span></div>
  </div>
  <div class="metric">
    <div class="metric-label">NIFTY</div>
    <div class="metric-value">{{ macro.nifty_current | default('--') }}</div>
  </div>
  <div class="metric">
    <div class="metric-label">India VIX</div>
    <div class="metric-value">{{ macro.india_vix | default('--') }}</div>
  </div>
  <div class="metric">
    <div class="metric-label">RBI Stance</div>
    <div class="metric-value">{{ macro.rbi_stance | default('--') }}</div>
  </div>
  {% if key_events %}
  <p><strong>Today's Key Events:</strong> {{ key_events | join(', ') }}</p>
  {% endif %}
</div>

<h2>Section 2: Top 5 Intraday Ideas</h2>
{% for trade in top_trades %}
<div class="card {{ trade.direction }}">
  <h3>{{ trade.ticker }} — {{ trade.direction | upper }} &nbsp;
    {% if trade.risk_flag %}<span class="risk-flag">⚠ {{ trade.risk_flag }}</span>{% endif %}
  </h3>
  <table>
    <tr><th>Entry Zone</th><th>Stop Loss</th><th>Target 1</th><th>Target 2</th><th>R:R</th><th>Horizon</th></tr>
    <tr>
      <td>{{ trade.entry_zone }}</td>
      <td>{{ trade.stop_loss }}</td>
      <td>{{ trade.target_1 }}</td>
      <td>{{ trade.target_2 | default('--') }}</td>
      <td>{{ trade.risk_reward }}</td>
      <td>{{ trade.time_horizon }}</td>
    </tr>
  </table>
  <p><strong>Setup:</strong> {{ trade.rationale }}</p>
  {% if trade.shap_factors %}
  <p><strong>Top signals:</strong> {{ trade.shap_factors | join(', ') }}</p>
  {% endif %}
</div>
{% endfor %}

<h2>Section 3: Options Ideas</h2>
<div class="card">
  {% if options_signals %}
  <table>
    <tr><th>Symbol</th><th>ATM IV</th><th>PCR</th><th>Max Pain</th><th>VRP Signal</th><th>IV Skew</th></tr>
    {% for sym, data in options_signals.items() %}
    <tr>
      <td>{{ sym }}</td>
      <td>{{ data.atm_iv | default('--') }}</td>
      <td>{{ data.pcr | default('--') }}</td>
      <td>{{ data.max_pain | default('--') }}</td>
      <td>{{ data.vrp_signal | default('--') }}</td>
      <td>{{ data.iv_skew | default('--') }}</td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <p>Options data not available. Run NSE options fetcher first.</p>
  {% endif %}
</div>

<h2>Section 4: Stocks to Watch</h2>
{% for stock in watch_list %}
<div class="card">
  <strong>{{ stock.ticker }}</strong> — {{ stock.reason }}
</div>
{% endfor %}

<footer>
  Generated by India Quant Trading Assistant | {{ report_date }} | For informational purposes only. Not investment advice.
</footer>
</body>
</html>"""


def generate_daily_report(as_of_date: str = None) -> str:
    """Generate daily HTML report. Returns path to generated file."""
    as_of_date = as_of_date or date.today().isoformat()
    logger.info(f"[DailyReport] Generating report for {as_of_date}")

    # Fetch macro regime
    try:
        from india_quant.agents.macro_analyst import _get_macro_regime
        macro = _get_macro_regime()
    except Exception as e:
        logger.warning(f"Macro data failed: {e}")
        macro = {"regime_label": "Unknown", "nifty_current": None, "india_vix": None, "rbi_stance": "unknown"}

    # Fetch top ML signals from DB
    top_trades = _fetch_top_ml_signals(as_of_date)

    # Fetch options signals
    options_signals = _fetch_options_summary(as_of_date)

    # Key events today
    key_events = _get_key_events(as_of_date)

    # Watch list (stocks near key levels)
    watch_list = _get_watch_list(as_of_date)

    template = Template(DAILY_TEMPLATE)
    html = template.render(
        report_date=as_of_date,
        macro=macro,
        top_trades=top_trades,
        options_signals=options_signals,
        key_events=key_events,
        watch_list=watch_list,
    )

    html_path = REPORTS_DIR / f"{as_of_date}.html"
    html_path.write_text(html)

    json_path = REPORTS_DIR / f"{as_of_date}.json"
    json_path.write_text(json.dumps({
        "date": as_of_date,
        "macro": macro,
        "top_trades": top_trades,
        "options_signals": options_signals,
        "key_events": key_events,
    }, default=str))

    logger.info(f"[DailyReport] Saved: {html_path}")
    return str(html_path)


def _fetch_top_ml_signals(as_of_date: str) -> list[dict]:
    """Get top 5 ML signal trades from DB."""
    try:
        from india_quant.data.db import get_session
        from sqlalchemy import text
        with get_session() as session:
            rows = session.execute(
                text("""
                    SELECT tp.ticker, tp.instrument, tp.direction, tp.entry_price,
                           tp.stop_loss, tp.target_1, tp.target_2, tp.risk_reward,
                           tp.rationale, tp.risk_status
                    FROM trade_proposal tp
                    WHERE tp.date = :d AND tp.risk_status = 'APPROVED'
                    ORDER BY tp.risk_reward DESC LIMIT 5
                """),
                {"d": as_of_date},
            ).fetchall()
        trades = []
        for r in rows:
            trades.append({
                "ticker": r[0], "instrument": r[1], "direction": r[2],
                "entry_zone": f"{r[3] * 0.995:.1f}–{r[3] * 1.005:.1f}",
                "stop_loss": r[4], "target_1": r[5], "target_2": r[6],
                "risk_reward": round(r[7], 2) if r[7] else None,
                "rationale": r[8], "time_horizon": "intraday",
                "risk_flag": None if r[9] == "APPROVED" else r[9],
                "shap_factors": [],
            })
        return trades
    except Exception as e:
        logger.warning(f"Could not fetch ML signals: {e}")
        return []


def _fetch_options_summary(as_of_date: str) -> dict:
    """Get options signal summary from DB."""
    try:
        from india_quant.signals.options_signals import OptionsSignalEngine
        ose = OptionsSignalEngine()
        result = ose.run_all(as_of_date)
        pcr = result.get("pcr", {})
        max_pain = result.get("max_pain", {})
        summary = {}
        for sym in ["NIFTY", "BANKNIFTY"]:
            summary[sym] = {
                "pcr": pcr.get(sym, {}).get("pcr"),
                "max_pain": max_pain.get(sym, {}).get("max_pain_strike"),
                "vrp_signal": "sell" if result.get("vrp", {}) else "neutral",
                "iv_skew": result.get("iv_skew", {}).get(sym),
            }
        return summary
    except Exception as e:
        logger.warning(f"Options summary failed: {e}")
        return {}


def _get_key_events(as_of_date: str) -> list[str]:
    """Check for key events: RBI, expiry, major earnings."""
    from datetime import date
    events = []
    d = date.fromisoformat(as_of_date)
    if d.weekday() == 3:  # Thursday
        events.append("NIFTY/BANKNIFTY Weekly F&O Expiry")
    from india_quant.config import cfg
    if as_of_date in cfg.rbi_policy_dates:
        events.append("RBI Monetary Policy Committee Decision")
    return events


def _get_watch_list(as_of_date: str) -> list[dict]:
    """Stocks near key technical levels."""
    try:
        from india_quant.data.db import get_session
        from sqlalchemy import text
        with get_session() as session:
            rows = session.execute(
                text("""
                    SELECT DISTINCT ticker FROM factor_scores
                    WHERE date = :d
                    AND abs(momentum_1) > 0.9
                    LIMIT 5
                """),
                {"d": as_of_date},
            ).fetchall()
        return [{"ticker": r[0], "reason": "Strong short-term momentum signal"} for r in rows]
    except Exception:
        return []
